### ISSUE TITLE
Eliminar información del objeto de token de respuesta del login

### ISSUE THREAD

**Issue by eamanu** [Portal-Pacientes-La-Rioja/portal_paciente_LR_backend#123]
Cuando se realiza el login, se retorna el ID y si es super admin, esto lo deberíamos poner encriptado en el payload del JWT de respuesta.

**Comment by ifdamianboden** [comment]
Emma, entonces ID y si es súper van encriptados o el ID como lo devuelvo
está bien y faltaría Vero lo de súper?

**Comment by eamanu** [comment]
>
>
>Emma, entonces ID y si es súper van encriptados o el ID como lo devuelvo
>está bien y faltaría Vero lo de súper?
> >
>
Si, habría que estudiar un poco a ver que nos ofrece el payload de JWT. (No
se la respuesta  que nos conviene)

**Comment by ifdamianboden** [comment]
Okk, lo veo.

**Comment by eamanu** [comment]
Fixed in https://github.com/Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/124
