### ISSUE TITLE
Revisar porque están duplicados los endpoints

### ISSUE THREAD

**Issue by eamanu** [Portal-Pacientes-La-Rioja/portal_paciente_LR_backend#49]
![image](https://user-images.githubusercontent.com/7605307/227803795-e1b78a98-4070-4a32-b349-a0ef802c794f.png)

**Comment by ifdamianboden** [comment]
Hola Emma, dale. Mañana ya estoy en Chilecito de nuevo y me pongo con las
tareas.

**Comment by ifdamianboden** [comment]
Separé los endpoint de instituciones.

**Comment by eamanu** [comment]
Corregí los endpoints que tenian "institution" en la definción del ApiRouter y tenían "Institutions" en la  definción del endpoint... ahora todos tienen "Institutions"
