### ISSUE TITLE
Fix duplicated code

### ISSUE THREAD

**Issue by eamanu** [Portal-Pacientes-La-Rioja/portal_paciente_LR_backend#86]
Se puede utilizar la variable que se consulta más arriba.

https://github.com/Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/blob/7429e8c8190532c67a987d3b455f78184fd9bbf9/app/gear/local/local_impl.py#L544

**Comment by ifdamianboden** [comment]
Esto ya estaba, no lo cerré
